{
 "title": "GRPC-IN",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "[M1][JAVA]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[JAVA] GRPC метрики",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Для отображения метрик grpc необходимо подключить ObservationGrpcServerInterceptor. Пример - [GrpcTemplateCoreServer.java#L40](https://gitlab.gitlab.bcs.ru/bm/common/template-core/-/blob/master/service/src/main/java/com/bcs/bm/templatecore/grpc/config/GrpcTemplateCoreServer.java?ref_type=heads#L40)"
   }
  },
  {
   "title": "[M1] [JAVA] [GRPC-IN] RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method)(rate(grpc_server_seconds_count{app=\"$service\"}[1m])) ",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-IN] Average Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum by (rpc_service, rpc_method)(\n    rate(grpc_server_seconds_sum{app=\"$service\"}[1m])\n  )\n  /\n  sum by (rpc_service, rpc_method)(\n    rate(grpc_server_seconds_count{app=\"$service\"}[1m])\n  )\n) * 1000",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-IN] Max Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (rpc_service, rpc_method)(\n  grpc_server_seconds_max{app=\"$service\"}\n) * 1000",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-IN] Active Connections by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method)(\n  grpc_server_active_seconds_count{app=\"$service\"}\n)",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-IN] RPS Received messages by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method)(\n  rate(grpc_server_received_total{app=\"$service\"}[1m])\n)",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-IN] RPS Sent messages by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (\n  rate(grpc_server_sent_total{app=\"$service\"}[1m])\n)",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  { "title": "[M1][OTEL]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "[OTEL] Подключение opentelemtry",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить трейсинг. Общий ликбез для всех [тут](https://confluence.bcs.ru/spaces/MB/pages/423119197/%D0%9A%D0%B0%D0%BA+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82+%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%B8%D0%BD%D0%B3+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+OpenTelemetry).\n\n### Java\nЕсли вы используете канареечный пайплайн, то трейсинг подключается автоматически, делать ничего дополнительно не нужно.\n\nЕсли у вас свой пайплайн и чарты, тогда нужно выполнить все шаги из [инструкции](https://confluence.bcs.ru/spaces/MB/pages/625206143/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+opentelemtry).\n\n### .NET\n\nВстраивается через библиотеку [BCS.Fintech.Tracing](https://gitlab.gitlab.bcs.ru/mybroker/backend/nuget/bcs.fintech.core/-/tree/master/package/src/BCS.Fintech.Tracing/BCS.Fintech.Tracing?ref_type=heads).\n\nВ [шаблон микросервиса](https://confluence.bcs.ru/spaces/MB/pages/539525396/%D0%9A%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81+%D0%B8%D0%B7+%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0) она уже подключена и настроена, поэтому все новые сервисы не нуждаются в дополнительных действиях.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-IN] RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['rpc.service'] || '/' || SpanAttributes['rpc.method']  as route,\n  count() / (${__interval_ms} / 1000) AS rps\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Server'\nGROUP BY time, SpanAttributes['rpc.service'], SpanAttributes['rpc.method']\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-IN] RPS by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  count() / (${__interval_ms} / 1000) AS code,\n  SpanAttributes['rpc.grpc.status_code'] as status_code\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Server'\nGROUP BY time, status_code\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-IN] P99 Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['rpc.service'] || '/' || SpanAttributes['rpc.method']  as route,\n  quantile(0.99)(Duration / 1000000) AS p99\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Server'\nGROUP BY time, SpanAttributes['rpc.service'], SpanAttributes['rpc.method']\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-IN] Max Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['rpc.service'] || '/' || SpanAttributes['rpc.method']  as route,\n  max(Duration / 1000000) AS max_duration\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Server'\nGROUP BY time, SpanAttributes['rpc.service'], SpanAttributes['rpc.method']\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [ISTIO]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Istio",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 82 },
     "options": {
      "content": "Метрики отображаются в случае, если ваш сервис вызывается через istio-gateway (в чартах сервиса должен быть VirtualService)"
     }
    },
    {
     "title": "[M1] [ISTIO] [GRPC-IN] RPS by HTTP Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(istio_requests_total{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"grpc\", destination_workload!=\"unknown\"}[1m])) by (response_code)",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "[M1] [ISTIO] [GRPC-IN] P50, P95, P99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(istio_request_duration_seconds_bucket{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"grpc\", destination_workload!=\"unknown\"}[1m])) by (le)\n) * 1000",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(istio_request_duration_seconds_bucket{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"grpc\", destination_workload!=\"unknown\"}[1m])) by (le)\n) * 1000",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(istio_request_duration_seconds_bucket{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"grpc\", destination_workload!=\"unknown\"}[1m])) by (le)\n) * 1000",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  }
 ]
}