{
 "title": "GRPC-OUT",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "[M1] [JAVA]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[JAVA] GRPC метрики",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Для отображения метрик grpc необходимо подключить ObservationGrpcClientInterceptor. Пример - [GrpcClientConfiguration.java](https://gitlab.gitlab.bcs.ru/trade-api/trade-api-bff-operations/-/blob/MB-220387-perevod-servisa-tradeapibffoperations-komandy-trad/service/src/main/java/com/bcs/bm/tradeapibffoperations/config/GrpcClientConfiguration.java#L38)"
   }
  },
  {
   "title": "[M1] [JAVA] [GRPC-OUT] RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (rate(grpc_client_seconds_count{app=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-OUT] Average Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (rate(grpc_client_seconds_sum{app=~\"$service\"}[$__rate_interval]))\n/\nsum by (rpc_service, rpc_method) (rate(grpc_client_seconds_count{app=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-OUT] Max Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (rpc_service, rpc_method) (grpc_client_seconds_max{app=~\"$service\"})",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-OUT] Active calls by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (grpc_client_active_seconds_count{app=~\"$service\"})",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-OUT] RPS Sent messages by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (rate(grpc_client_sent_total{app=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [GRPC-OUT] RPS Received messages by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (rate(grpc_client_received_total{app=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{rpc_service}}/{{rpc_method}}"
    }
   ]
  },
  { "title": "[M1] [OTEL]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "[OTEL] Подключение opentelemtry",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить трейсинг. Общий ликбез для всех [тут](https://confluence.bcs.ru/spaces/MB/pages/423119197/%D0%9A%D0%B0%D0%BA+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82+%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%B8%D0%BD%D0%B3+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+OpenTelemetry).\n\n### Java\nЕсли вы используете канареечный пайплайн, то трейсинг подключается автоматически, делать ничего дополнительно не нужно.\n\nЕсли у вас свой пайплайн и чарты, тогда нужно выполнить все шаги из [инструкции](https://confluence.bcs.ru/spaces/MB/pages/625206143/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+opentelemtry).\n\n### .NET\n\nВстраивается через библиотеку [BCS.Fintech.Tracing](https://gitlab.gitlab.bcs.ru/mybroker/backend/nuget/bcs.fintech.core/-/tree/master/package/src/BCS.Fintech.Tracing/BCS.Fintech.Tracing?ref_type=heads).\n\nВ [шаблон микросервиса](https://confluence.bcs.ru/spaces/MB/pages/539525396/%D0%9A%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81+%D0%B8%D0%B7+%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0) она уже подключена и настроена, поэтому все новые сервисы не нуждаются в дополнительных действиях.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-OUT] RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['rpc.service'] || '/' || SpanAttributes['rpc.method']  as route,\n  count() / (${__interval_ms} / 1000) AS rps\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Client'\nGROUP BY time, SpanAttributes['rpc.service'], SpanAttributes['rpc.method']\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-OUT] P99 Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['rpc.service'] || '/' || SpanAttributes['rpc.method']  as route,\n  quantile(0.99)(Duration / 1000000) AS p99\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Client'\nGROUP BY time, SpanAttributes['rpc.service'], SpanAttributes['rpc.method']\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-OUT] RPS by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  count() / (${__interval_ms} / 1000) AS code,\n  SpanAttributes['rpc.grpc.status_code'] as status_code\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Client'\nGROUP BY time, status_code\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [GRPC-OUT] Max Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['rpc.service'] || '/' || SpanAttributes['rpc.method']  as route,\n  max(Duration / 1000000) AS max_duration\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['rpc.system'] = 'grpc'\n  AND SpanKind = 'Client'\nGROUP BY time, SpanAttributes['rpc.service'], SpanAttributes['rpc.method']\nORDER BY time"
    }
   ]
  }
 ]
}