{
 "title": "JAVA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "${VAR_SERVICE}" }
  ]
 },
 "panels": [
  {
   "title": "Дашборд микросервиса ${service}",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "[Логи](https://kibana.mybroker.global.bcs/app/data-explorer/discover?security_tenant=global#?_a=%28discover:%28columns:!%28time,jsn.message,jsn.level,jsn.traceId%29,isDirty:!f,sort:!%28%29%29,metadata:%28indexPattern:'7f779a30-f651-11ea-abae-cdd0768658e0',view:discover%29%29&_g=%28filters:!%28%28meta:%28alias:!n,disabled:!f,index:'7f779a30-f651-11ea-abae-cdd0768658e0',key:jsn.serviceName,negate:!f,params:%28query:'${service}'%29,type:phrase,value:'trade-api-market-data-connector'%29,query:%28match_phrase:%28jsn.serviceName:'trade-api-market-data-connector'%29%29%29%29,refreshInterval:%28pause:!t,value:0%29,time:%28from:now-15m,to:now%29%29&_q=h@6146871)\n\n[Трейсы](https://grafana-m1.bcs.ru/grafana/d/beybwnq4q0dtsf/clickhouse-otel-dashboard?orgId=1&from=now-5m&to=now&timezone=browser&var-datasource=beyxcx6ont728a&var-serviceName=${service}&var-trace_id=)"
   }
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "[M1] [JAVA] [CPU] System usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (instance) (system_cpu_usage{app=\"$service\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [CPU] Process usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (instance) (process_cpu_usage{app=\"$service\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [OKD3] [CPU] Usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{container_name=~\"${service}(-green|-blue)?$\"}\n  )\n) by (pod_name) \n/\nsum(\n  container_spec_cpu_quota{container_name=~\"${service}(-green|-blue)?$\"}\n  /\n  container_spec_cpu_period{container_name=~\"${service}(-green|-blue)?$\"}\n) by (pod_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "[M1] [JAVA] [RAM] Non-heap usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance) (jvm_memory_used_bytes{app=\"$service\", area=\"nonheap\"})*100 / sum by (instance) (jvm_memory_max_bytes{app=\"$service\",area=\"nonheap\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [RAM] Heap usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance) (jvm_memory_used_bytes{app=\"$service\", area=\"heap\"})*100 / sum by (instance) (jvm_memory_max_bytes{app=\"$service\",area=\"heap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[M1] [OKD3] [RAM] Memory Usage by POD (Percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (\n  container_memory_usage_bytes{container_name=~\"${service}(-green|-blue)?$\"})\nby (pod_name)\n/\nsum (\n  container_spec_memory_limit_bytes{container_name=~\"${service}(-green|-blue)?$\"}\n) by (pod_name)\n* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[M1] [OKD3] [RAM] Memory Usage by POD (GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=~\"${service}(-green|-blue)?$\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "container_memory_working_set_bytes{container_name=~\"${service}(-green|-blue)?$\"}",
       "legendFormat": "current usage POD: {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "[M1] [JAVA] [JVM] Threads (daemons) by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (jvm_threads_daemon_threads{app=\"$service\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Threads (live) by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (jvm_threads_live_threads{app=\"$service\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Threads (peak) by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (jvm_threads_peak_threads{app=\"$service\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "[M1] [JAVA] [JVM] GC Pause Rate by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{app=\"${service}\"}[5m])",
       "legendFormat": "{{instance}} - {{action}} {{cause}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] GC Pause Duration (per second) by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{app=\"${service}\"}[5m])",
       "legendFormat": "{{instance}} - {{action}} {{cause}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] GC Max Pause by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{app=\"${service}\"}",
       "legendFormat": "{{instance}} - {{action}} {{cause}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap/Non-heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "[M1] [JAVA] [JVM] Non-Heap Compressed Class Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"Compressed Class Space\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Non-Heap Metaspace by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"Metaspace\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Heap CodeCache by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"CodeCache\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Heap G1 Old Gen by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"G1 Old Gen\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Heap G1 Survivor Space by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"G1 Survivor Space\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Heap G1 Eden Space by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"G1 Eden Space\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "[M1] [JAVA] [JVM] Error & Warn Logs by POD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(logback_events_total{app=\"${service}\", level=\"error\"}[5m])",
       "legendFormat": "{{instance}} - error"
      },
      {
       "expr": "rate(logback_events_total{app=\"${service}\", level=\"warn\"}[5m])",
       "legendFormat": "{{instance}} - warn"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [JVM] Log Events Rate by Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (level) (rate(logback_events_total{app=\"${service}\"}[5m]))",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  }
 ]
}