{
 "title": "JVM",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Java micrometer",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить библиотеки\n```groovy\n    implementation \"io.micrometer:micrometer-core\"\n    implementation \"io.micrometer:micrometer-registry-prometheus\"\n```\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Heap/Non-Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "[M1] [JAVA] [JVM] Heap G1 Eden Space by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"G1 Eden Space\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Heap G1 Survivor Space by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"G1 Survivor Space\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Heap G1 Old Gen by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"G1 Old Gen\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Heap CodeCache by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"CodeCache\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Non-Heap Metaspace by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"Metaspace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Non-Heap Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, id) (jvm_memory_used_bytes{app=\"$service\", id=\"Compressed Class Space\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "[M1] [JAVA] [JVM] GC Max Pause by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{app=\"${service}\"}",
     "legendFormat": "{{instance}} - {{action}} {{cause}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] GC Pause Duration (per second) by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{app=\"${service}\"}[5m])",
     "legendFormat": "{{instance}} - {{action}} {{cause}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] GC Pause Rate by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{app=\"${service}\"}[5m])",
     "legendFormat": "{{instance}} - {{action}} {{cause}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "[M1] [JAVA] [JVM] Threads (peak) by POD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_threads_peak_threads{app=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Threads (live) by POD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_threads_live_threads{app=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Threads (daemons) by POD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_threads_daemon_threads{app=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "[M1] [JAVA] [JVM] Error & Warn Logs by POD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{app=\"${service}\", level=\"error\"}[5m])",
     "legendFormat": "{{instance}} - error"
    },
    {
     "expr": "rate(logback_events_total{app=\"${service}\", level=\"warn\"}[5m])",
     "legendFormat": "{{instance}} - warn"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [JVM] Log Events Rate by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (level) (rate(logback_events_total{app=\"${service}\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}