{
 "title": "KAFKA-IN",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "[M1][JAVA]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Java micrometer",
   "type": "text",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 1 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить библиотеки\n```groovy\n    implementation \"io.micrometer:micrometer-core\"\n    implementation \"io.micrometer:micrometer-registry-prometheus\"\n```\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Average Processing Time by Listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spring_kafka_listener_seconds_sum{app=\"${service}\"}[1m]) / rate(spring_kafka_listener_seconds_count{app=\"${service}\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Max Processing Time by Listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_max{app=\"${service}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Max lag by Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_max{app=\"${service}\"}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Lag by Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumer_fetch_manager_records_lag{app=\"${service}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Connection Events By Consumer and POD ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_connection_close_total{app=\"${service}\"}[1m])",
     "legendFormat": "Close - {{client_id}} - {{instance}}"
    },
    {
     "expr": "rate(kafka_consumer_connection_creation_total{app=\"${service}\"}[1m])",
     "legendFormat": "Create - {{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Polls per second by Listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "polls/s" } },
   "targets": [
    {
     "expr": "rate(sum by (name) (spring_kafka_listener_seconds_count{app=\"${service}\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Records per second by Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_consumer_fetch_manager_records_consumed_total{app=\"${service}\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [KAFKA-IN] Records per second by Listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (client_id) (rate(kafka_consumer_fetch_manager_records_consumed_total{app=\"${service}\"}[1m]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "[M1][OTEL]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "[OTEL] Подключение opentelemtry",
   "type": "text",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 31 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить трейсинг. Общий ликбез для всех [тут](https://confluence.bcs.ru/spaces/MB/pages/423119197/%D0%9A%D0%B0%D0%BA+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82+%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%B8%D0%BD%D0%B3+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+OpenTelemetry).\n\n### Java\nЕсли вы используете канареечный пайплайн, то трейсинг подключается автоматически, делать ничего дополнительно не нужно.\n\nЕсли у вас свой пайплайн и чарты, тогда нужно выполнить все шаги из [инструкции](https://confluence.bcs.ru/spaces/MB/pages/625206143/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+opentelemtry).\n\n### .NET\n\nВстраивается через библиотеку [BCS.Fintech.Tracing](https://gitlab.gitlab.bcs.ru/mybroker/backend/nuget/bcs.fintech.core/-/tree/master/package/src/BCS.Fintech.Tracing/BCS.Fintech.Tracing?ref_type=heads).\n\nВ [шаблон микросервиса](https://confluence.bcs.ru/spaces/MB/pages/539525396/%D0%9A%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81+%D0%B8%D0%B7+%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0) она уже подключена и настроена, поэтому все новые сервисы не нуждаются в дополнительных действиях.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [OTEL] RPS by Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['messaging.destination.name'] as topic,\n  count() / (${__interval_ms} / 1000) AS rps\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['messaging.system'] = 'kafka'\n  AND SpanAttributes['messaging.system'] != ''\n  AND SpanAttributes['messaging.operation'] = 'process'\nGROUP BY time, topic\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] P99 by Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['messaging.destination.name'] as topic,\n  quantile(0.99)(Duration / 1000000) AS p99\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['messaging.system'] = 'kafka'\n  AND SpanAttributes['messaging.system'] != ''\n  AND SpanAttributes['messaging.operation'] = 'process'\nGROUP BY time, topic\nORDER BY time"
    }
   ]
  }
 ]
}