{
 "title": "POSTGRES",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Java micrometer",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить библиотеки\n```groovy\n    implementation \"io.micrometer:micrometer-core\"\n    implementation \"io.micrometer:micrometer-registry-prometheus\"\n```\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "[M1] [JAVA]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "[M1] [JAVA] [POSTGRES] HikariCP Connections Count by POD",
   "type": "timeseries",
   "description": "Подключения к БД",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (hikaricp_connections_active{app=\"${service}\"}) by(instance)",
     "legendFormat": "Active connection - {{ instance }}"
    },
    {
     "expr": "sum (hikaricp_connections_pending{app=\"${service}\"}) by(instance)",
     "legendFormat": "Pending threads - {{ instance }}"
    },
    {
     "expr": "sum(hikaricp_connections_idle{app=\"$service\"}) by(instance)",
     "legendFormat": "Idle connection - {{ instance }}"
    },
    {
     "expr": "sum(hikaricp_connections_timeout_total{app=\"$service\"}) by(instance)",
     "legendFormat": "Timeout connection - {{ instance }}"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [POSTGRES] HikariCP Connections Latency by Pod",
   "type": "timeseries",
   "description": "Показывает среднее время соденения",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (instance) \r\n(\r\n\t(\r\n\t\tirate\r\n\t\t\t(hikaricp_connections_usage_seconds_sum{app=\"$service\"}[$__rate_interval])\r\n\t) \r\n\t/\r\n\t(\r\n\t\tirate\r\n\t\t\t(hikaricp_connections_usage_seconds_count{app=\"$service\"}[$__rate_interval])\r\n\t)\r\n)",
     "legendFormat": "Usage time - {{ instance }}"
    },
    {
     "expr": "avg by (instance) \r\n(\r\n\t(\r\n\t\tirate\r\n\t\t\t(hikaricp_connections_creation_seconds_sum{app=\"$service\"}[$__rate_interval])\r\n\t) \r\n\t/\r\n\t(\r\n\t\tirate\r\n\t\t\t(hikaricp_connections_creation_seconds_count{app=\"$service\"}[$__rate_interval])\r\n\t)\r\n)",
     "legendFormat": "Creation time - {{ instance }}"
    },
    {
     "expr": "avg by (instance) \r\n(\r\n\t(\r\n\t\tirate\r\n\t\t\t(hikaricp_connections_acquire_seconds_sum{app=\"$service\"}[$__rate_interval])\r\n\t) \r\n\t/\r\n\t(\r\n\t\tirate\r\n\t\t\t(hikaricp_connections_acquire_seconds_count{app=\"$service\"}[$__rate_interval])\r\n\t)\r\n)",
     "legendFormat": "Acquired time - {{ instance }}"
    }
   ]
  },
  { "title": "[M1] [OTEL]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "[OTEL] Подключение opentelemtry",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить трейсинг. Общий ликбез для всех [тут](https://confluence.bcs.ru/spaces/MB/pages/423119197/%D0%9A%D0%B0%D0%BA+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82+%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%B8%D0%BD%D0%B3+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+OpenTelemetry).\n\n### Java\nЕсли вы используете канареечный пайплайн, то трейсинг подключается автоматически, делать ничего дополнительно не нужно.\n\nЕсли у вас свой пайплайн и чарты, тогда нужно выполнить все шаги из [инструкции](https://confluence.bcs.ru/spaces/MB/pages/625206143/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+opentelemtry).\n\n### .NET\n\nВстраивается через библиотеку [BCS.Fintech.Tracing](https://gitlab.gitlab.bcs.ru/mybroker/backend/nuget/bcs.fintech.core/-/tree/master/package/src/BCS.Fintech.Tracing/BCS.Fintech.Tracing?ref_type=heads).\n\nВ [шаблон микросервиса](https://confluence.bcs.ru/spaces/MB/pages/539525396/%D0%9A%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81+%D0%B8%D0%B7+%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0) она уже подключена и настроена, поэтому все новые сервисы не нуждаются в дополнительных действиях.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [OTEL] [POSTGRES] P99 by DB and Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  'db: ' || SpanAttributes['db.name'] || ' ' || SpanAttributes['db.operation'] as statement,\n  quantile(0.99)(Duration / 1000000) AS p99\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['db.system'] = 'postgresql'\n  AND SpanAttributes['db.operation'] != ''\nGROUP BY time, statement\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [POSTGRES] RPS by DB and Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  'db: ' || SpanAttributes['db.name'] || ' ' || SpanAttributes['db.operation'] as statement,\n  count() / (${__interval_ms} / 1000) AS qps\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n    AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['db.system'] = 'postgresql'\n  AND SpanAttributes['db.operation'] != ''\nGROUP BY time, SpanAttributes['db.operation'], SpanAttributes['db.name']\nORDER BY time"
    }
   ]
  }
 ]
}