{
 "title": "RAM/CPU",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "[M1] [OKD3]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[M1] [OKD3] [CPU] Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{container_name=~\"${service}(-green|-blue)?$\"}\n  )\n) by (pod_name) \n/\nsum(\n  container_spec_cpu_quota{container_name=~\"${service}(-green|-blue)?$\"}\n  /\n  container_spec_cpu_period{container_name=~\"${service}(-green|-blue)?$\"}\n) by (pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[M1] [OKD3] [RAM] Memory Usage by POD (GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=~\"${service}(-green|-blue)?$\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "container_memory_working_set_bytes{container_name=~\"${service}(-green|-blue)?$\"}",
     "legendFormat": "current usage POD: {{pod_name}}"
    }
   ]
  },
  {
   "title": "[M1] [OKD3] [RAM] Memory Usage by POD (Percent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (\n  container_memory_usage_bytes{container_name=~\"${service}(-green|-blue)?$\"})\nby (pod_name)\n/\nsum (\n  container_spec_memory_limit_bytes{container_name=~\"${service}(-green|-blue)?$\"}\n) by (pod_name)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "[M1] [JAVA]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Java micrometer",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить библиотеки\n```groovy\n    implementation \"io.micrometer:micrometer-core\"\n    implementation \"io.micrometer:micrometer-registry-prometheus\"\n```\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [JAVA] [CPU] Process usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (process_cpu_usage{app=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [CPU] System usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (system_cpu_usage{app=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [RAM] Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{app=\"$service\", area=\"heap\"})*100 / sum by (instance) (jvm_memory_max_bytes{app=\"$service\",area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [RAM] Non-heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{app=\"$service\", area=\"nonheap\"})*100 / sum by (instance) (jvm_memory_max_bytes{app=\"$service\",area=\"nonheap\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}