{
 "title": "REDIS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[M1] [JAVA]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "[JAVA] Redis метрики",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "Метрики появтяся при использовании библиотеки `implementation 'org.springframework.boot:spring-boot-starter-data-redis'`"
     }
    },
    {
     "title": "[M1] [JAVA] [REDIS] Average Latency by Command",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (command) (rate(lettuce_command_completion_seconds_sum{app=\"$service\"}[5m])) \n/ \nsum by (command) (rate(lettuce_command_completion_seconds_count{app=\"$service\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [REDIS] Max Latency by Command",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (command) (lettuce_command_completion_seconds_max{app=\"$service\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[M1] [JAVA] [REDIS] RPS by Command",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (command) (rate(lettuce_command_completion_seconds_count{app=\"$service\"}[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "[M1] [TRAVOLTA]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "[Travolta] Redis метрики",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "Метрики появтяся при использовании библиотеки [travolta-jedis-starter](https://gitlab.gitlab.bcs.ru/bm/common/bm-travolta/-/tree/master/travolta-jedis-starter)"
     }
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Max and Avg connection Acquire time by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_acquire_seconds_max{app=\"$service\"}[1m]",
       "legendFormat": "max {{instance}}|{{redis_instance}}"
      },
      {
       "expr": "rate(travolta_jedis_pool_connection_acquire_seconds_sum{app=\"$service\"}[1m]) / rate(travolta_jedis_pool_connection_acquire_seconds_count{app=\"$service\"}[1m])",
       "legendFormat": "avg {{instance}}|{{redis_instance}}"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Max and Avg connection Release time by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_release_seconds_max{app=\"$service\"}[1m]",
       "legendFormat": "max {{instance}}|{{redis_instance}}"
      },
      {
       "expr": "rate(travolta_jedis_pool_connection_release_seconds_sum{app=\"$service\"}[1m]) / rate(travolta_jedis_pool_connection_release_seconds_count{app=\"$service\"}[1m])",
       "legendFormat": "avg {{instance}}|{{redis_instance}}"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Max and Avg connection Usage time by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_usage_seconds_max{app=\"$service\"}[1m]",
       "legendFormat": "max {{instance}}|{{redis_instance}}"
      },
      {
       "expr": "rate(travolta_jedis_pool_connection_usage_seconds_sum{app=\"$service\"}[1m]) / rate(travolta_jedis_pool_connection_usage_seconds_count{app=\"$service\"}[1m])",
       "legendFormat": "avg {{instance}}|{{redis_instance}}"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Max and Avg connection Make time by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_factory_make_seconds_max{app=\"$service\"}",
       "legendFormat": "max {{instance}}|{{redis_instance}}"
      },
      {
       "expr": "rate(travolta_jedis_pool_connection_factory_make_seconds_sum{app=\"$service\"}[1m]) / rate(travolta_jedis_pool_connection_factory_make_seconds_count{app=\"$service\"}[1m])",
       "legendFormat": "avg {{instance}}|{{redis_instance}}"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Max and Avg connection Destroy time by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_factory_destroy_seconds_max{app=\"$service\"}",
       "legendFormat": "max {{instance}}|{{redis_instance}}"
      },
      {
       "expr": "rate(travolta_jedis_pool_connection_factory_destroy_seconds_sum{app=\"$service\"}[1m]) / rate(travolta_jedis_pool_connection_factory_destroy_seconds_count{app=\"$service\"}[1m])",
       "legendFormat": "avg {{instance}}|{{redis_instance}}"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Rate connection usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(travolta_jedis_pool_connection_usage_seconds_count{app=\"$service\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Activate connections by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_active{app=\"$service\"}",
       "legendFormat": "{{instance}}|{{redis_instance}}"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] Idle connections by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_idle{app=\"$service\"}",
       "legendFormat": "{{instance}}|{{redis_instance}}"
      }
     ]
    },
    {
     "title": "[M1] [TRAVOLTA] [REDIS] All connections by Pod and Redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "expr": "travolta_jedis_pool_connection_all{app=\"$service\"}",
       "legendFormat": "{{instance}}|{{redis_instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[M1] [OTEL]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "[OTEL] Подключение opentelemtry",
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "Для отображения метрик необходимо в сервисе подключить трейсинг. Общий ликбез для всех [тут](https://confluence.bcs.ru/spaces/MB/pages/423119197/%D0%9A%D0%B0%D0%BA+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82+%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%B8%D0%BD%D0%B3+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+OpenTelemetry).\n\n### Java\nЕсли вы используете канареечный пайплайн, то трейсинг подключается автоматически, делать ничего дополнительно не нужно.\n\nЕсли у вас свой пайплайн и чарты, тогда нужно выполнить все шаги из [инструкции](https://confluence.bcs.ru/spaces/MB/pages/625206143/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+opentelemtry).\n\n### .NET\n\nВстраивается через библиотеку [BCS.Fintech.Tracing](https://gitlab.gitlab.bcs.ru/mybroker/backend/nuget/bcs.fintech.core/-/tree/master/package/src/BCS.Fintech.Tracing/BCS.Fintech.Tracing?ref_type=heads).\n\nВ [шаблон микросервиса](https://confluence.bcs.ru/spaces/MB/pages/539525396/%D0%9A%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81+%D0%B8%D0%B7+%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0) она уже подключена и настроена, поэтому все новые сервисы не нуждаются в дополнительных действиях.\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "[M1] [OTEL] [REDIS] P99 Latency by Command",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanName  as route,\n  quantile(0.99)(Duration / 1000000) AS p99\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['db.system'] = 'redis'\nGROUP BY time, SpanName\nORDER BY time"
      }
     ]
    },
    {
     "title": "[M1] [OTEL] [REDIS] RPS by Command",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  count() / (${__interval_ms} / 1000) AS rps,\n  SpanName as status_code\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['db.system'] = 'redis'\nGROUP BY time, status_code\nORDER BY time"
      }
     ]
    }
   ]
  }
 ]
}