{
 "title": "REST-OUT",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "[M1] [OTEL]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[OTEL] Подключение opentelemtry",
   "type": "text",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 1 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить трейсинг. Общий ликбез для всех [тут](https://confluence.bcs.ru/spaces/MB/pages/423119197/%D0%9A%D0%B0%D0%BA+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82+%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%B8%D0%BD%D0%B3+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+OpenTelemetry).\n\n### Java\nЕсли вы используете канареечный пайплайн, то трейсинг подключается автоматически, делать ничего дополнительно не нужно.\n\nЕсли у вас свой пайплайн и чарты, тогда нужно выполнить все шаги из [инструкции](https://confluence.bcs.ru/spaces/MB/pages/625206143/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+opentelemtry).\n\n### .NET\n\nВстраивается через библиотеку [BCS.Fintech.Tracing](https://gitlab.gitlab.bcs.ru/mybroker/backend/nuget/bcs.fintech.core/-/tree/master/package/src/BCS.Fintech.Tracing/BCS.Fintech.Tracing?ref_type=heads).\n\nВ [шаблон микросервиса](https://confluence.bcs.ru/spaces/MB/pages/539525396/%D0%9A%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81+%D0%B8%D0%B7+%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0) она уже подключена и настроена, поэтому все новые сервисы не нуждаются в дополнительных действиях.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [OTEL] [REST-OUT] RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['http.request.method'] || ' ' || SpanAttributes['server.address'] as anyFull,\n  count() / (${__interval_ms} / 1000) AS rps\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['url.full'] is not null\n  AND SpanAttributes['url.full'] != ''\nGROUP BY time, SpanAttributes['server.address'], SpanAttributes['http.request.method']\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [REST-OUT] RPS by HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  count() / (${__interval_ms} / 1000) AS code,\n  ': ' || SpanAttributes['http.response.status_code'] || ', host: ' || SpanAttributes['server.address'] as status_code\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['url.full'] is not null\n  AND SpanAttributes['url.full'] != ''\n  AND SpanAttributes['http.response.status_code'] is not null\n  AND SpanAttributes['http.response.status_code'] != ''\nGROUP BY time, SpanAttributes['server.address'], SpanAttributes['http.response.status_code']\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [REST-OUT] P99 Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['http.request.method'] || ' ' || SpanAttributes['server.address'] as full,\n  quantile(0.99)(Duration / 1000000) AS p99\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['url.full'] is not null\n  AND SpanAttributes['url.full'] != ''\nGROUP BY time, SpanAttributes['server.address'], SpanAttributes['http.request.method']\nORDER BY time"
    }
   ]
  }
 ]
}