{
 "title": "REST-IN",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Сервис (через app)",
    "query": {
     "query": "label_values(kube_pod_labels,label_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "[M1] [JAVA]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Java micrometer",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить библиотеки\n```groovy\n    implementation \"io.micrometer:micrometer-core\"\n    implementation \"io.micrometer:micrometer-registry-prometheus\"\n```\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "[M1] [JAVA] [REST-IN] RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{app=\"$service\", uri!~\"^/(manage|actuator).*\"})) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [REST-IN] Max Response Time by Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{app=\"$service\", uri!~\"^/(manage|actuator).*\"} * 1000) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[M1] [JAVA] [REST-IN] RPS by HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$service\", uri!~\"^/(manage|actuator).*\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "[M1] [OTEL]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Opentelemtry",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "Для отображения метрик необходимо в сервисе подключить трейсинг. Общий ликбез для всех [тут](https://confluence.bcs.ru/spaces/MB/pages/423119197/%D0%9A%D0%B0%D0%BA+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82+%D1%82%D1%80%D0%B5%D0%B9%D1%81%D0%B8%D0%BD%D0%B3+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+OpenTelemetry).\n\n### Java\nЕсли вы используете канареечный пайплайн, то трейсинг подключается автоматически, делать ничего дополнительно не нужно.\n\nЕсли у вас свой пайплайн и чарты, тогда нужно выполнить все шаги из [инструкции](https://confluence.bcs.ru/spaces/MB/pages/625206143/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+opentelemtry).\n\n### .NET\n\nВстраивается через библиотеку [BCS.Fintech.Tracing](https://gitlab.gitlab.bcs.ru/mybroker/backend/nuget/bcs.fintech.core/-/tree/master/package/src/BCS.Fintech.Tracing/BCS.Fintech.Tracing?ref_type=heads).\n\nВ [шаблон микросервиса](https://confluence.bcs.ru/spaces/MB/pages/539525396/%D0%9A%D0%B0%D0%BA+%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C+%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81+%D0%B8%D0%B7+%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0) она уже подключена и настроена, поэтому все новые сервисы не нуждаются в дополнительных действиях.\n"
   }
  },
  {
   "title": "[M1] [OTEL] [REST-IN] RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['http.route'] as route,\n  count() / (${__interval_ms} / 1000) AS rps\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['http.route'] is not null\n  AND SpanAttributes['http.route'] != ''\nGROUP BY time, route\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [REST-IN] RPS by HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  count() / (${__interval_ms} / 1000) AS code,\n  SpanAttributes['http.status_code'] as status_code\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['http.route'] is not null\n  AND SpanAttributes['http.route'] != ''\n  AND SpanAttributes['http.status_code'] is not null\n  AND SpanAttributes['http.status_code'] != ''\nGROUP BY time, status_code\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [REST-IN] P99 Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['http.route'] as route,\n  quantile(0.99)(Duration / 1000000) AS p99\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['http.route'] is not null\n  AND SpanAttributes['http.route'] != ''\nGROUP BY time, route\nORDER BY time"
    }
   ]
  },
  {
   "title": "[M1] [OTEL] [REST-IN] P95 Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(Timestamp, toIntervalSecond(${__interval_ms} / 1000)) AS time,\n  SpanAttributes['http.route'] as route,\n  quantile(0.95)(Duration / 1000000) AS p95\nFROM otel.otel_traces\nWHERE\n  $__timeFilter(Timestamp)\n  AND ServiceName in ('${service}', 'bm-${service}')\n  AND SpanAttributes['http.route'] is not null\n  AND SpanAttributes['http.route'] != ''\nGROUP BY time, route\nORDER BY time"
    }
   ]
  },
  { "title": "[M1] [ISTIO]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Istio",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "Метрики отображаются в случае, если ваш сервис вызывается через istio-gateway (в чартах сервиса должен быть VirtualService)"
   }
  },
  {
   "title": "[M1] [ISTIO] [REST-IN] RPS by HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"http\", destination_workload!=\"unknown\"}[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "[M1] [ISTIO] [REST-IN] P50, P95, P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(istio_request_duration_seconds_bucket{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"http\", destination_workload!=\"unknown\"}[1m])) by (le)\n) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(istio_request_duration_seconds_bucket{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"http\", destination_workload!=\"unknown\"}[1m])) by (le)\n) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(istio_request_duration_seconds_bucket{destination_service_name=~\"(bm-)?${service}(-green|-blue)?$\", request_protocol=\"http\", destination_workload!=\"unknown\"}[1m])) by (le)\n) * 1000",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}